name: Build Frontend and Backend


on:
  workflow_dispatch:

    
jobs:
  backend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: furrycon-server/furrycon

    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: |
          ./furrycon-server/furrycon/build/libs/*.jar
          !./furrycon-server/furrycon/build/libs/*-plain.jar
  
  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: furrycon

    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ./furrycon/dist
